### PR TITLE
Work around Stay bugs and improve edits

### PR DESCRIPTION
**Pull request by ghost**
This pull request makes several changes:
- Improves the example code
- Makes edits more versatile and work more "as expected"
- Works around bugs in stays
  Commit messages should give further clarification.

### CODE REVIEW

**Comment by miv-ableton** [comment]
LGTM, but let's ensure Travis tests green.

**Comment by ala-ableton** [comment]
I will also build it on Windows, just in case :smile:

**Comment by ala-ableton** [comment]
It was not easy to test (had to rebase on top of the latest master and sync rhea to use @jbo-ableton's fork), but I can confirm that it builds on Windows!

**Comment by ghost** [comment]
@miv-ableton @ala-ableton The required changes have been merged in Rhea and I have updated the pull request accordingly. Also I have added doxygen documentation as suggested by @gck-ableton.

**Pull request merged**
